vqgan_ckpt: 0
vqvae_ckpt: 0
vqgan_spade_ckpt: 0
name: ddpm
segconv: 0
spade_input_channel: 64

# Have to be derived from VQ-GAN Latent space dimensions
diffusion_img_size: 64
diffusion_depth_size: 8
diffusion_num_channels: 8
dim_mults: ???
results_folder: /data/private/autoPET/medicaldiffusion_results/results/checkpoints/ddpm
results_folder_postfix: 'diff'
load_milestone: -1

batch_size: 4
num_workers: 4
logger: wandb
objective: pred_x0
save_and_sample_every: 600
denoising_fn: Unet3D
diffusion: SemanticGaussianDiffusion
train_lr: 1e-4
timesteps: 500 # number of steps 300
sampling_timesteps: 250 # number of sampling timesteps (using ddim for faster inference [see citation for ddim paper])
loss_type: l1 # L1 or L2
train_num_steps: 700000 # total training steps
gradient_accumulate_every: 2 # gradient accumulation steps
ema_decay: 0.995 # exponential moving average decay
amp: False # turn on mixed precision
num_sample_rows: 1
gpus: 0
cond_scale: 1.5
