name: AutoPET
root_dir: /misc/data/private/autoPET/autopet_3d/train/   #/data/private/autoPET/imagesTr #/misc/data/private/autoPET/autopet_3d_wo_artifacts/train/ct # /misc/data/private/autoPET/autopet_3d/train/ct
image_channels: 1
label_nc: 37
